import { mkdir, writeFile } from "node:fs/promises"
import path from "node:path"

export async function writeLocalSnapshots(parts: ItemData[], shopItems: PartsShopData[], resources: ResourceData[]): Promise<void> {
    const snapshotDir = path.resolve(process.cwd(), "src/data/synced")
    await mkdir(snapshotDir, { recursive: true })

    const header = "/* Auto-generated by sync tooling. Do not edit manually. */\n\n"
    const partsSnapshot = `${header}const allParts = ${JSON.stringify(parts, null, 4)} as ItemData[]\n\nexport default allParts\n`
    const shopSnapshot = `${header}const allPartsShopItems = ${JSON.stringify(shopItems, null, 4)} as PartsShopData[]\n\nexport default allPartsShopItems\n`
    const resourcesSnapshot = `${header}const allResources = ${JSON.stringify(resources, null, 4)} as ResourceData[]\n\nexport default allResources\n`

    await writeFile(path.join(snapshotDir, "partsCatalogSnapshot.ts"), partsSnapshot, "utf8")
    await writeFile(path.join(snapshotDir, "partsShopSnapshot.ts"), shopSnapshot, "utf8")
    await writeFile(path.join(snapshotDir, "resourcesSnapshot.ts"), resourcesSnapshot, "utf8")
}
